# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm:
  ros__parameters:
    joints:
      - link_1 to base_link
      - link_2 to link_1
      - link_3 to link_2
      - link_4 to link_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity